/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-primary-fixed": "#131b2e",
              "tertiary-container": "#001a42",
              "on-primary": "#ffffff",
              "on-tertiary-fixed-variant": "#004395",
              "inverse-primary": "#bec6e0",
              "inverse-on-surface": "#eaf1ff",
              "secondary-fixed": "#6ffbbe",
              "on-surface": "#0b1c30",
              "surface": "#f8f9ff",
              "error-container": "#ffdad6",
              "secondary-fixed-dim": "#4edea3",
              "on-secondary-container": "#00714d",
              "on-error": "#ffffff",
              "surface-container-lowest": "#ffffff",
              "secondary-container": "#6cf8bb",
              "surface-variant": "#d3e4fe",
              "outline-variant": "#c6c6cd",
              "on-secondary-fixed": "#002113",
              "surface-dim": "#cbdbf5",
              "primary-fixed": "#dae2fd",
              "error": "#ba1a1a",
              "inverse-surface": "#213145",
              "secondary": "#006c49",
              "surface-bright": "#f8f9ff",
              "on-tertiary-container": "#3980f4",
              "on-surface-variant": "#45464d",
              "surface-container": "#e5eeff",
              "on-background": "#0b1c30",
              "surface-container-highest": "#d3e4fe",
              "on-tertiary-fixed": "#001a42",
              "tertiary": "#000000",
              "tertiary-fixed": "#d8e2ff",
              "tertiary-fixed-dim": "#adc6ff",
              "surface-container-high": "#dce9ff",
              "on-primary-fixed-variant": "#3f465c",
              "on-primary-container": "#7c839b",
              "on-secondary": "#ffffff",
              "on-secondary-fixed-variant": "#005236",
              "primary-container": "#131b2e",
              "surface-tint": "#565e74",
              "on-error-container": "#93000a",
              "outline": "#76777d",
              "surface-container-low": "#eff4ff",
              "primary-fixed-dim": "#bec6e0",
              "primary": "#000000",
              "on-tertiary": "#ffffff",
              "background": "#f8f9ff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "md": "1.5rem",
              "lg": "2.5rem",
              "base": "4px",
              "xl": "4rem",
              "gutter": "24px",
              "sm": "1rem",
              "xs": "0.5rem",
              "container-max": "1200px"
      },
      "fontFamily": {
              "caption-sm": ["Inter"],
              "label-md": ["Inter"],
              "display-lg": ["Inter"],
              "title-md": ["Inter"],
              "headline-lg": ["Inter"],
              "body-lg": ["Inter"],
              "body-md": ["Inter"],
              "headline-lg-mobile": ["Inter"]
      },
      "fontSize": {
              "caption-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
